// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Curated by hand instead of autogenerated: the docs/ folder is flat, so an
 * autogenerated sidebar would list all 9 files alphabetically with no sense
 * of what to read first. Grouped here into the shape the content already has --
 * three "Design Rationale" essays share an audience and a title suffix, and
 * "Get Started" reads in a specific order (why, then mental model, then FAQ).
 *
 * Every category here holds 2+ docs on purpose: a single-item category still
 * gets a generated-index page, and Infima's card grid lays one card out
 * lopsided with dead space beside it -- so "Why Lattice" (origin alone) was
 * folded into "Get Started" instead of standing alone.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Get Started',
      link: {
        type: 'generated-index',
        description: 'Why Lattice exists, the mental model behind it, and scenario-driven answers for adopting and using it.',
      },
      items: ['origin', 'how-it-works', 'practical-guide'],
    },
    {
      type: 'category',
      label: 'Design Rationale',
      link: {
        type: 'generated-index',
        description: "Why specific molecules and protocols are designed the way they are -- for readers who want the reasoning, not just the mechanics.",
      },
      items: [
        'framework-intelligence',
        'collaborative-judgment',
        'architecture-compass',
        'agents/verification',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {
        type: 'generated-index',
        description: 'Config file schema and how Lattice ships as a plugin across multiple AI coding tools.',
      },
      items: ['configuration', 'plugins'],
    },
  ],
};

export default sidebars;
